Fix build error when LWIP_IGMP disabled
[Description]
Build error when LWIP_IGMP is set to 0 in lwipopts.h:
error: implicit declaration of function 'netif_set_igmp_mac_filter' [-Wimplicit-function-declaration]

[Root Cause]
IGMP related code was not embraced with macro LWIP_IGMP

[Fix]
Embrace IGMP related code with macro LWIP_IGMP

[Testing]
Local compile ok

[Reviewers]
Gannicus Guo

[Port proposal]
non-general

Change-Id: 80e04f8ecf3111f0b3912b1765915757

Signed-off-by: Qingling Wu <qingling.wu@nxp.com>