Issue: WSW-39070 Fix build errors caused by macros are not fully defined.
[Issue]
RT1170 + IW416
Failed to build wifi_cli_over_ble_wu if diable CONFIG_11K and CONFIG_11V and CONFIG_ROAMING in wifi_config.h.

[Analysis]
When disable CONFIG_11K and CONFIG_11V and CONFIG_ROAMING and enable CONFIG_11R, wlan_set_rssi_low_threshold will be referenced by test_wlan_rssi_low_threshold. But wlan_set_rssi_low_threshold only be declared when enable CONFIG_11K or CONFIG_11V or CONFIG_ROAMING.

'undefined reference to `wlan_set_rssi_low_threshold' build erros occures.

[Fix]
Declare wlan_set_rssi_low_threshold when enable CONFIG_11R.

[Validation done]
Success to build wifi_cli and wifi_cli_over_ble_wu by GCC.

[Open Issues/Todo]
None

[Reviewers]
Gannicus Guo, Sandip Dalvi, Abhinav Kulkarni.

Signed-off-by: Qiankun Li <qiankun.li@nxp.com>