Fix build errors in wifi_cli_static
[Description]
 error: 'POOL_ID4_POOL_SZ' undeclared (first use in this function)

[Root Cause]
not define POOL_ID4_POOL_SZ

[Fix]
define pool size

[Testing]
Build pass

[Reviewers]
Gannicus Guo, Hui Bai, Sanjay Yadav, Li Long

[Port proposal]
general

Change-Id: I58bd2189a5dcae4f2b2363212d7896e9e2d25242
Signed-off-by: Gang Li <gang.li_1@nxp.com>