Issue: WSFD-590 Linker error suring compilation of wifi_wpa_supplicant app
[Issue]
Linking error: undefined reference to `wlan_enable_uap_11d'

[Fix]
In wifi_uap.c file call wifi_enable_uap_11d_support() directly instead of wlan apis

[Validation done]
Compilation Success for mcux and armgcc

[Open Issues/Todo]
None

[Reviewers]
Sandip Dalvi, Supriya Inamdar, Abhinav Kulkarni

Signed-off-by: Sanjay Yadav <sanjay.yadav@nxp.com>