Issue: WSW-34547 [RW612][Matter over Wi-Fi]Fix wlan.c does not correctly include wlan_fw_bin_len variable [Issue] Fix compile error of "undefined reference to 'wlan_fw_bin_len'" [Analyze] wlan_fw_bin and wlan_fw_bin_len are defined in wlan_bt_fw.h, Matter doesn't include this file and cause compile error. [Fix] Move the definition to wlan.c, and modify the declaration to extern include in wlan_fw_bin_len This modification also can avoid duplicate definition. [Validation done] Test passed with wifi_cli [Open Issues/Todo] None [reviewers] Sandip Dalvi, Gannicus Guo Signed-off-by: xinyuhong <xinyu.hong@nxp.com>