Fix otbr build errors caused by no definition of g_flt_cfg.
[Description]
ot-nxp/third_party/nxp_matter_support/github_sdk/sdk_next/repo/mcuxsdk/middleware/wifi_nxp/wlcmgr/wlan.c:12346:13:
 error: 'g_flt_cfg' undeclared (first use in this function)
12346 |     memset(&g_flt_cfg, 0, sizeof(g_flt_cfg));

[Root Cause]
1. g_flt_cfg is a global variable controlled by a macro CONFIG_MEF_CFG.
2. CONFIG_MEF_CFG isn't enabled in wifi_config.h of OTbr example.

[Fix]
1. Add CONFIG_MEF_CFG control to functions releated to g_flt_cfg.

[Port proposal]
non-general

[Testing]
Success to build wifi_cli.

[Reviewers]
Gannicus Guo, Mayur Mansharamani.

Change-Id: I96a3b22de1d72b2fd81378fbfc7af5d5be467dd5
Signed-off-by: Qiankun Li <qiankun.li@nxp.com>