Fix build warnings on STA-only build
[Description]
Fixed build warnings observed in STA-only build:
error: control reaches end of non-void function [-Werror=return-type]

[Root Cause]
In STA-only mode, a function hwlan_uap_get_beacon_period had no return value, leading to compiler errors.

[Fix]
Guarded wlan_uap_get_beacon_period with UAP_SUPPORT.

[Testing]
Validated with both STA-only and default builds.

[Open Issues/Todo]
None

[Reviewers]
Gannicus Guo, Pankaj Razdan

[Port Proposal]
General, applicable for Zephyr & FreeRTOS

Change-Id: 711c7a8c-c60d-11f0-8cbb-00155dddf836

Signed-off-by: Manav Chotalia <manavashwinbhai.chotalia@nxp.com>