Issue: MCRED-698 [MATTER] Build issue due to wifi undeclared variable
[Issue]
[MATTER] Build issue due to wifi undeclared variable.
middleware/wifi_nxp/wlcmgr/wlan.c:1207:5: error: 'wlan_is_manual' undeclared (first use in this function); did you mean 'is_manual'?
middleware/wifi_nxp/wlcmgr/wlan.c:1286:5: error: 'is_hs_handshake_done' undeclared (first use in this function)
middleware/wifi_nxp/wlcmgr/wlan.c:6929:41: error: 'wakelock' undeclared (first use in this function)
The CONFIG_HOST_SLEEP is enabled but CONFIG_POWER_MANAGER is disabled.

[Fix]
Move definitions of those parameters out of CONFIG_POWER_MANAGER flag.

[Validation done]
The compilation is ok.

[Reviewers]
Gannicus Guo, Sandip Dalvi, Li Long, Maochen Wang

Signed-off-by: Hui Bai <hui.bai@nxp.com>