Issue: WSW-34433 Fix build warning with ARMGCC 2.13.rel1 caused by strcasecmp
Do not merge back to master branch.
[Issue]
Found below build warning with ARMGCC 2.13.rel1 due to new ARMGCC lib doesn't has "strcasecmp"
cli\cli_utils.c: In function 'a2hex':
C:\c\pkg\middleware\wifi_nxp\cli\cli_utils.c:73:9: warning: implicit declaration of function 'strcasecmp'; did you mean 'strncmp'? [-Wimplicit-function-declaration]
   73 |     if (strcasecmp("0x", s) == 0)

[Fix]
Use recommended "strncmp" and check both "0x" and "0X" cases.

[Validation done]
1. Compilation ok.
2. Verified ok of commands that uses this API.

[Reviewers]
Gannicus Guo, Li Long, Maochen Wang

Signed-off-by: Hui Bai <hui.bai@nxp.com>