Issue: WSW-25577 and CONNRT-266 [1170][9177] Resolving build errors and stabilizing the wifi_nxp master branch.
[Issue]
Error received from matter compiler tool.
Error: comparison of unsigned expression in '>= 0' is always true for below line
        else if (rate_index >= MLAN_RATE_INDEX_MCS0 && rate_index <= MLAN_RATE_INDEX_MCS127)
Value of rate_index variable(which is of type uint8 from calling function) will always be greater or equal to
MLAN_RATE_INDEX_MCS0 macro whose value is 0U.

Warnings received from armgcc compiler
warning: 'rv' may be used uninitialized in this function [-Wmaybe-uninitialized]

Warnings received from IAR compiler:
middleware\wifi_nxp\wlcmgr\wlan_enhanced_tests.c(717) : Warning[Pe188]: enumerated type mixed with another type
middleware\wifi_nxp\wifidriver\mlan_11ax.c(141)       : Warning[Pa182]: bit mask appears to contain significant bits that do not affect the result

[Fix]
Fixed build errors and warnings of vaious compilers.
Corrected the copyright values.

[Verification]
Built wifi_cli app successfully on IAR, armgcc and mcuXpresso compilers.

[Open Issues/Todo]
None.

[Review]
Abhinav Kulkarni, Sandip Dalvi, Supriya Inamdar, Sanjay Yadav.

Signed-off-by: Keval Thakker <keval.thakker@nxp.com>