Issue: WSFD-590 [FreeRTOS] Add wpa supplicant and hostapd support
[Issue]
SDIO RX aggregation fails to get rd port.
Error: wlan_get_rd_port : Returning FAILURE

[Fix]
1. Changed logic to check the available buffer space for next port.
2. Earlier port was getting marked as used even if buffer space check.
3. So port was considered for read but actual read was not getting performed.
4. Hence after some time issue in get rd port observed.

[Validation done]
Tested scan and connect, connect.

[Open Issues/Todo]
None

[Reviewers]
Supriya Inamdar, Abhinav Kulkarni, Sachin Patki

Signed-off-by: Sandip Dalvi <sandip.dalvi@nxp.com>