Fix IAR build error caused by TWT commit.
[Description]
1. wifidriver/incl/mlan_ioctl.h(3183) : Error[Pe077]:
    this declaration has no storage class or type specifier
2. wifidriver/incl/mlan_ioctl.h(3183) : Error[Pe065]: expected a ";"
3. wifidriver/incl/mlan_ioctl.h(3211) : Error[Pe020]:
    identifier "mlan_ds_btwt_cfg" is undefined

[Root Cause]
Build error.

[Fix]
Modify definition of mlan_ds_btwt_set_t.

[Testing]
1. Success to build flash_release wifi_cli by IAR.

[Open Issues/Todo]
None

[Reviewers]
Gannicus Guo, Sandip Dalvi, Pankaj Razdan.

Change-Id: If5f9bbbf2b4c9ded3dee162b81acfa599c8287ed
Signed-off-by: Qiankun Li <qiankun.li@nxp.com>