Fix coex (wifi_supplicant+bt+ot) build error for RW612 Zephyr.
[Description]
When build coex (wifi_supplicant+bt+ot), there is build error shows:
/modules/crypto/mbedtls/include/mbedtls/check_config.h:374:2: error: #error 'MBEDTLS_KEY_EXCHANGE_ECJPAKE_ENABLED defined, but not all prerequisites'
  374 | #error 'MBEDTLS_KEY_EXCHANGE_ECJPAKE_ENABLED defined, but not all prerequisites'

[Root Cause]
Both MBEDTLS_USE_PSA_CRYPTO and MBEDTLS_KEY_EXCHANGE_ECJPAKE_ENABLED are defined, but PSA_WANT_ALG_JPAKE is not defined.

[Fix]
define PSA_WANT_ALG_JPAKE in wpa_supp_els_pkc_mbedtls_config.h

[Testing]
wifi supplicant build pass.
coex (wifi_supplicant+bt+ot) build pass.

[Open Issues/Todo]
build pass

[Reviewers]
Gannicus Guo

[Port proposal]
general

Change-Id: 211f704a-2afc-11f0-bf76-6ffd709702a9
Signed-off-by: Maochen Wang <maochen.wang@nxp.com>